<?php ?>
<!DOCTYPE html>
<html ng-app="app">
<head ng-controller="titulo">
	<title>PHP Test</title>
	<!-- CSS -->
	<link href="../asset/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<!-- CSS -->
	<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<span class="navbar-brand" ng-model="titulo"><img src="" class="brand" /></span>
		</div>
	</div>
</nav>
</head>
<body>
<form class="">
	<span class=""></span>
</form>

<!-- Scripts JS -->
<script src="../asset/js/bootstrap.min.js" type="text/javascript"></script>
<script src="../asset/js/jquery-1.11.3.js" type="text/javascript"></script>
<script src="../asset/js/underscore.js" type="text/javascript"></script>
<script src="../asset/js/angular.min.js" type="text/javascript"></script>
<script src="../asset/js/app.js" type="text/javascript"></script>
<!-- Scripts JS -->
</body>
</html>
