<?php ?>
<<!DOCTYPE html>
<html>
<head>
	<title></title>
	<!-- CSS -->
	<link href="../asset/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<!-- CSS -->
</head>
<body>
<p class="navbar-text navbar-right">Hola</p>



<!-- Scripts JS -->
<script src="../asset/js/bootstrap.min.js" type="text/javascript"></script>
<script src="../asset/js/jquery-1.11.3.js" type="text/javascript"></script>
<script src="../asset/js/underscore.js" type="text/javascript"></script>
<script src="../asset/js/angular.min.js" type="text/javascript"></script>
<script src="../asset/js/app.js" type="text/javascript"></script>
<!-- Scripts JS -->
</body>
</html>
